"""Research-side data access helpers."""

from .research_client import (
    AkshareResearchSource,
    ComparisonReport,
    DataDomain,
    DomainPolicy,
    FinancialDataset,
    GmResearchSource,
    QMTResearchSource,
    ResearchClient,
    SnapshotBundle,
    SnapshotDiffArtifact,
    SnapshotDiffReport,
    SourceName,
    TabularDataset,
    TushareResearchSource,
    diff_snapshots,
    load_snapshot,
    write_diff_report,
)
from .research_database import (
    build_factor_price_cache,
    detect_source_conflicts,
    ensure_maintenance_layer,
    insert_source_evidence,
    start_batch,
    upsert_daily_bar_delta,
)
from .research_database_client import ResearchDatabaseClient, connect_readonly
from .starbridge_gics4_industry import (
    DEFAULT_QMT_GICS4_CACHE,
    DEFAULT_QMT_GICS4_SUMMARY,
    fetch_qmt_gics4_industry_map,
    load_cached_qmt_gics4_industry_map,
    write_qmt_gics4_industry_cache,
)

__all__ = [
    "AkshareResearchSource",
    "ComparisonReport",
    "DataDomain",
    "DEFAULT_QMT_GICS4_CACHE",
    "DEFAULT_QMT_GICS4_SUMMARY",
    "DomainPolicy",
    "FinancialDataset",
    "GmResearchSource",
    "QMTResearchSource",
    "ResearchClient",
    "SnapshotBundle",
    "SnapshotDiffArtifact",
    "SnapshotDiffReport",
    "SourceName",
    "TabularDataset",
    "TushareResearchSource",
    "ResearchDatabaseClient",
    "build_factor_price_cache",
    "connect_readonly",
    "diff_snapshots",
    "detect_source_conflicts",
    "ensure_maintenance_layer",
    "fetch_qmt_gics4_industry_map",
    "insert_source_evidence",
    "load_snapshot",
    "load_cached_qmt_gics4_industry_map",
    "start_batch",
    "upsert_daily_bar_delta",
    "write_qmt_gics4_industry_cache",
    "write_diff_report",
]
