"""Research-side data access helpers."""

from .research_client import (
    AkshareResearchSource,
    ComparisonReport,
    DataDomain,
    DomainPolicy,
    FinancialDataset,
    QMTResearchSource,
    ResearchClient,
    SnapshotBundle,
    SnapshotDiffArtifact,
    SnapshotDiffReport,
    SourceName,
    TabularDataset,
    TushareResearchSource,
    diff_snapshots,
    load_snapshot,
    write_diff_report,
)
from .starbridge_gics4_industry import (
    DEFAULT_QMT_GICS4_CACHE,
    DEFAULT_QMT_GICS4_SUMMARY,
    fetch_qmt_gics4_industry_map,
    load_cached_qmt_gics4_industry_map,
    write_qmt_gics4_industry_cache,
)

__all__ = [
    "AkshareResearchSource",
    "ComparisonReport",
    "DataDomain",
    "DEFAULT_QMT_GICS4_CACHE",
    "DEFAULT_QMT_GICS4_SUMMARY",
    "DomainPolicy",
    "FinancialDataset",
    "QMTResearchSource",
    "ResearchClient",
    "SnapshotBundle",
    "SnapshotDiffArtifact",
    "SnapshotDiffReport",
    "SourceName",
    "TabularDataset",
    "TushareResearchSource",
    "diff_snapshots",
    "fetch_qmt_gics4_industry_map",
    "load_snapshot",
    "load_cached_qmt_gics4_industry_map",
    "write_qmt_gics4_industry_cache",
    "write_diff_report",
]
